import Navbar from '@/components/Navbar'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import {Toaster} from 'react-hot-toast'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-background flex flex-col items-center'>
        <NextTopLoader />
        <Navbar />
        <Toaster />
        {children}
      </body>
    </html>
  )
}
